/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeropuerto;

import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class InterfazVuelo extends javax.swing.JFrame {

    /**
     * Creates new form InterfazVuelo
     */
    public InterfazVuelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButImportarDatos = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();
        ButConfirmar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        InfoPasajero = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        ButIngresarPasajero = new javax.swing.JButton();
        ButRevisarLista = new javax.swing.JButton();
        Ruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        ButImportarDatos.setText("Importar datos");
        ButImportarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButImportarDatosActionPerformed(evt);
            }
        });

        ButCancelar.setText("Cancelar");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        ButConfirmar.setText("Confirmar");
        ButConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConfirmarActionPerformed(evt);
            }
        });

        InfoPasajero.setText("                             Información del pasajero");

        Nombre.setText("Nombre");

        Apellido.setText("Apellido");

        Id.setText("ID");

        Tel.setText("Teléfono");

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        ButIngresarPasajero.setText("Ingresar pasajero");
        ButIngresarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButIngresarPasajeroActionPerformed(evt);
            }
        });

        ButRevisarLista.setText("Revisar Lista");
        ButRevisarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRevisarListaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese porfavor la dirección donde se encuentra el archivo con la información.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ButImportarDatos)
                                    .addGap(29, 29, 29)
                                    .addComponent(Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ButConfirmar)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(330, 330, 330))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nombre)
                                .addComponent(Apellido)
                                .addComponent(Id))
                            .addGap(413, 413, 413))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Tel)
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InfoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(txtNombres)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButIngresarPasajero)
                        .addGap(10, 10, 10)
                        .addComponent(ButRevisarLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButCancelar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButImportarDatos)
                    .addComponent(Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ButConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoPasajero)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Apellido))
                                .addGap(33, 33, 33)
                                .addComponent(Id))
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButRevisarLista)
                    .addComponent(ButIngresarPasajero)
                    .addComponent(ButCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButConfirmarActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void ButImportarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButImportarDatosActionPerformed
        String ruta = Ruta.getText();
        File f = new File(ruta);
        if (f.exists()) {
            try {
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + ruta);
            } catch (IOException e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encuentra el archivo\n" + ruta, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButImportarDatosActionPerformed

    private void ButIngresarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButIngresarPasajeroActionPerformed
        if (txtNombres.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese el nombre de el pasajero");
            return;
        }
         if (txtApellidos.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese el apellido de el pasajero");
            return;
        }
         if (txtID.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese la identificacion de el pasajero");
            return;
        }
         if (txtTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese el telefono  de el pasajero");
            return;
        
         }
         
       
    }//GEN-LAST:event_ButIngresarPasajeroActionPerformed

    private void ButRevisarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRevisarListaActionPerformed
        InterfazListasVuelos in = new InterfazListasVuelos();
        in.setVisible(true);
    }//GEN-LAST:event_ButRevisarListaActionPerformed

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_ButCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButConfirmar;
    private javax.swing.JButton ButImportarDatos;
    private javax.swing.JButton ButIngresarPasajero;
    private javax.swing.JButton ButRevisarLista;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel InfoPasajero;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Ruta;
    private javax.swing.JLabel Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
